[package]
name = "autokuma"
version = "0.0.0"
edition = "2021"

[dependencies]
bollard = { version = "0.15.0" }
confique = { version = "0.2.5", default-features = false, features = ["toml"] }
cute_custom_default = { version = "2.1.0" }
derivative = { version = "2.2.0" }
futures-util = { version = "0.3.30" }
itertools = { version = "0.12.0" }
rust_socketio = { git = "https://github.com/1c3t3a/rust-socketio.git", rev = "9ccf67b", features = [
    "async",
] }
serde = { version = "1.0.194", features = ["derive"] }
serde_alias = { version = "0.0.2" }
serde_json = { version = "1.0.111" }
serde_merge = { version = "0.1.3" }
serde_with = { version = "3.4.0" }
serde-inline-default = { version = "0.1.1" }
strum = { version = "0.25.0", features = ["derive"] }
tokio = { version = "1.35.1", features = ["full"] }
toml = { version = "0.8.8" }
